### PR TITLE
Schema/ftp

### PR DESCRIPTION
**Pull request by gmD3v**
ftp config schemas

### CODE REVIEW

**Comment by galindocode** [comment]
A device could have several ftp server in the configs.
Could include ftp config as arrays with a string id, its common that are one single ftp server in the configs, but when we have a device with several ftp configs will be a headache 👀

**Comment by gmD3v** [comment]
> A device could have several ftp server in the configs. Could include ftp config as arrays with a string id, its common that are one single ftp server in the configs, but when we have a device with several ftp configs will be a headache 👀

All right, check the new commit where I fix that 71245a95d2a4625cec2b2e2f69f6d64c944bc646

**Comment by galindocode** [comment]
Useing FileZilla as reference for FTP Settings, there are a config called `Encryption`.
image

Do you think about it? Do you think it would be appropriate to include it?

**Comment by gmD3v** [comment]
idk, devices could have such configurations? I mean, maybe the devices only have basic ftp configurations.

**Comment by galindocode** [comment]
This config is for a server that need this info, for example a server with tls. 
In hanwha this params is not requested, but when a device need this info?

**Comment by galindocode** [comment]
THis is Bosh ftp UI. Say `encryption`
image

**Comment by galindocode** [comment]
Pls, check another brands of vms, alarms, biometrics, cameras, nvrs and search the ftp config, and check if use the `Encryption` param

**Comment by gmD3v** [comment]
Then it might be a good idea to include it. Could it be like a checkbox or should it be a select like fillezilla?

**Comment by galindocode** [comment]
The selector is better. Although I think first investigate this params
Because can be only an optional config in any ftp connection. First investigate before add in schema


________________________________

**Comment by gmD3v** [comment]
Implicit FTP:
In implicit mode, security is automatically established as soon as the connection to the FTP server is initiated. This is usually done using SSL/TLS (Secure Sockets Layer/Transport Layer Security) to encrypt all communication between client and server. The standard port for implicit FTP is port 990. This mode is less commonly used than explicit, but some servers still support it.

Explicit FTP:
In explicit mode, security is established after the client connects to the FTP server, but before sending any login information or file data. This means that the client and server first make an unencrypted connection, and then the client must send a specific command (such as "AUTH TLS" or "AUTH SSL") to request security. Once security is established, all communication is encrypted using SSL/TLS. The standard port for explicit FTP is port 21.

Plain FTP:
Unencrypted FTP, or plain FTP, is the most basic mode of FTP in which no form of encryption is used to protect the transmitted information. In this mode, both commands and data, including usernames and passwords, are transmitted in plain text, which means that they are vulnerable to interception and data theft. Port 21 is used for this mode.

**Comment by gmD3v** [comment]
Active Mode:
In active mode, the FTP client opens a local data port (ephemeral port) and sends a PORT command to the FTP server to inform it of the data port it has opened. The FTP server then initiates the data connection from its control port (port 20 by default) to the data port specified by the client. In this mode, it is the client that listens for incoming connections from the server.

Active mode can be problematic in some network environments, as it implies that the server will attempt to connect to the client, which may be blocked by firewalls or routers that restrict incoming connections. However, this mode is useful in situations where the client has a firewall and not the server.

Passive Mode:
In passive mode, the initiative for the data connection is taken by the FTP client. The client sends a PASV command to the server, requesting the server to open a data port and inform it of the address and port on which it is listening. Once the server responds with an IP address and port, the client initiates the data connection to the server.

Passive mode is usually preferred in environments where there are firewall or NAT (Network Address Translation) restrictions that make incoming connections to the client difficult. In addition, passive mode can be more secure, as only the client initiates data connections.

**Comment by galindocode** [comment]
Excellent, now do you think that this propertie must be include in the config schema?

**Comment by gmD3v** [comment]
sure, if they are a bit more parametrized environments then this would be of use

**Comment by galindocode** [comment]
If you answer is 'yes', so what return drivers as `driver.hanwha_camera` when the camera havent this propertie in ftp section?

**Comment by gmD3v** [comment]
in that case that kind of drivers could use "plain" ftp, that is the default option without encryption

**Comment by galindocode** [comment]
Nice, now pls include this info in schemas guide for make the merge

**Comment by gmD3v** [comment]
It's already included in [494f909](https://github.com/Netsocs-Team/driver.sdk_go/pull/12/commits/494f90941f0fd9f300928f9cd5da9451e4f2ad47) commit

**Comment by galindocode** [comment]
Sorry, I speak about that info:
image
image
image

**Comment by gmD3v** [comment]
Okay, it´s done

**Pull request merged**
