### PR TITLE
feat: add card type support when adding a card to an AC

### PR DESCRIPTION
**Pull request by cuervodelviento**
I added the new getSupportedCardType config to get info on the cards supported by the device and the value type supported.

also updated the setCardToPersonAC to receive instead an array of a cardValue and its cardType.

### CODE REVIEW

**Comment by galindocode** [comment]
Hi Angel, to keep compatibility and simplicity of `setCardToPersonAC` config, I suggest when is a card with another type use another config, this make the SDK simple, in several Access Control hadware of 'card' concept is generic, and have not a type, only is 'a card'.

For QR card, I suggest create one new config called `setQRToPersonAC` with an array of values of "QRs" for that user.

## Why use `setQRToPersonAC` config and use not a `type-value` as propose you?

If Netsocs need add many people in many devices, and this people must use QRs, Netsocs will need send a message that ensure that are the QR which will assign a that person.

### Using `getSupportedCardTypes` config the flow would be like this:

1. Netsocs send to device `getSupportedCardTypes`.
2. Netsocs must identifier which is the QR type for use.
3. Netsocs must identifier of data type (string, numeric, alphanumeric, etc) for can send to device.

This flow have parameteres as `cardType` that can be 'qr', 'QR', 'qrCode', 'QRCode', etc. To avoid this, it would be necessary to define a word for ever that are a card of type 'qr', this definition would means define all card types, this could cause a trouble because a brand can change with anothers brand.

This flow have parameters as `valueType` that can be of multple types, for example `hex`, this could cause a trouble because a brand coudl have a hexadecimal format, and `68,6f,6c,61` or `0x8,0xf,0xc,0x1`, etc, this make that the who send the message must handle those `valueType`s and also there are that create aditional documentation that cover all cases and developers must handle this translation if is required.

### Using `setQRToPersonAC` config the flow would be like this:
1. Netsocs send an array of values in string
2. Driver expect a string and make the convertion to the format that is required for it.

If the driver is not QR compliant it returns an error, but usually the driver manual says whether or not it is qr compliant.

## Conclusion

The main differenct between this two ways is: The sense the flow, 

first flow make
netsocs -> driver
driver -> netsocs
netsocs -> driver

second flow make
netsocs -> driver

This sense keep the KISS pattern, remember that netsocs and driver sdk philosophy is keep simple and easy.

**Comment by galindocode** [comment]
I suggest keep the `getSupportedCardTypes` for info purposes.

**Comment by galindocode** [comment]
> Hi Angel, to keep compatibility and simplicity of `setCardToPersonAC` config, I suggest when is a card with another type use another config, this make the SDK simple, in several Access Control hadware of 'card' concept is generic, and have not a type, only is 'a card'.
> 
> For QR card, I suggest create one new config called `setQRToPersonAC` with an array of values of "QRs" for that user.
> 
> ## Why use `setQRToPersonAC` config and use not a `type-value` as propose you?
> If Netsocs need add many people in many devices, and this people must use QRs, Netsocs will need send a message that ensure that are the QR which will assign a that person.
> 
> ### Using `getSupportedCardTypes` config the flow would be like this:
> 1. Netsocs send to device `getSupportedCardTypes`.
> 2. Netsocs must identifier which is the QR type for use.
> 3. Netsocs must identifier of data type (string, numeric, alphanumeric, etc) for can send to device.
> 
> This flow have parameteres as `cardType` that can be 'qr', 'QR', 'qrCode', 'QRCode', etc. To avoid this, it would be necessary to define a word for ever that are a card of type 'qr', this definition would means define all card types, this could cause a trouble because a brand can change with anothers brand.
> 
> This flow have parameters as `valueType` that can be of multple types, for example `hex`, this could cause a trouble because a brand coudl have a hexadecimal format, and `68,6f,6c,61` or `0x8,0xf,0xc,0x1`, etc, this make that the who send the message must handle those `valueType`s and also there are that create aditional documentation that cover all cases and developers must handle this translation if is required.
> 
> ### Using `setQRToPersonAC` config the flow would be like this:
> 1. Netsocs send an array of values in string
> 2. Driver expect a string and make the convertion to the format that is required for it.
> 
> If the driver is not QR compliant it returns an error, but usually the driver manual says whether or not it is qr compliant.
> 
> ## Conclusion
> The main differenct between this two ways is: The sense the flow,
> 
> first flow make netsocs -> driver driver -> netsocs netsocs -> driver
> 
> second flow make netsocs -> driver
> 
> This sense keep the KISS pattern, remember that netsocs and driver sdk philosophy is keep simple and easy.

@cuervodelviento What do you think?

**Comment by cuervodelviento** [comment]
I now have a better understanding of the one-way Driver philosophy! Following this pattern, it makes sense to skip the step of querying first and instead create a new schema for QRCode assignment.

Now, I have a small doubt. What can we do about other types of cards, like smart cards, proximity cards that are from different brands or formats (like Mifare K1, Wiegand, chipcards)? Should we include new schemas like “SetAddMifareK1” and so on? As one device can support various types of cards, when setting a card, how can we know the right way to store the card value?

**Comment by galindocode** [comment]
Yes! Just as qr can be there or not, it is the same principle with the other types. When a device have several card types, the driver will use one config for each card type, this would allow to include a custon value for each card type and include additional information in case that type of card requires it, which was a limitation using cardType and cardValue as in the schema update of this PR

**Pull request closed without merging**
